name: fizzy-dev

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3006:3006"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - /home/cbr4l0k/Documents/projects/fizzy_storage/storage:/rails/storage
    environment:
      - RAILS_ENV=development
      - SOLID_QUEUE_IN_PUMA=false
    command: >
      bash -c "
        bundle install &&
        bin/rails db:prepare &&
        bin/rails db:seed &&
        bin/rails server -p 3006 -b 0.0.0.0
      "
volumes:
  bundle_cache:
